language: node_js
node_js:
  - v10
before_install:
  - npm install --global lerna
install:
  - lerna bootstrap
script:
  - lerna run test
deploy:
  - provider: script
    script:
      - ./packages/sharec-web-site/scripts/deploy.sh
    on:
      branches:
        only:
          - master
